### ISSUE TITLE
Rails/API

### ISSUE THREAD

**Issue by joelvh** [cypriss/mouth#1]
Hi,

I've been looking for a simple way to implement custom analytics with graphs/charts baked in. Been considering Librato Metrics so far, but this also seems like a simple implementation.

How could I either host mouth as an endpoint on Heroku or collect metrics within a Rails app (rather than running a separate daemon)?

Thanks!

**Comment by cypriss** [comment]
Didn't see your comment until now, sorry! Mouth is a bit of a dead project -- I recommend Librato :)
